autoDetectFormat: true
autoSelectOnPointClick: true
autosave: false
defaultAnnotationFormat: yolo
defaultDirectory: ''
deleteShapeKey: Ctrl+Backspace
finishDrawingKey: Esc
focusOnSelect: true
fontSize: 12
lineThickness: 2
thumbnailSize: 59
yoloModelPath: ''
zoomOnSelect: true
zoomOnSelectLevel: fit
