autoDetectFormat: true
autoSelectOnPointClick: true
autosave: true
defaultAnnotationFormat: yolo
defaultDirectory: /Users/christian/SyncThing/Bilder/Photos
deleteShapeKey: Ctrl+Backspace
finishDrawingKey: Esc
focusOnSelect: true
fontSize: 12
gpuAcceleration: true
lineThickness: 2
maxRecentPaths: 10
recentPaths:
- /Users/christian/SyncThing/Bilder/Stock Images
theme: dark
thumbnailCacheEnabled: true
thumbnailCacheMaxMb: 500
thumbnailSize: 59
yoloModelPath: ''
zoomOnSelect: true
zoomOnSelectLevel: fit
