autoSelectOnPointClick: true
autosave: false
defaultDirectory: ''
deleteShapeKey: Ctrl+Backspace
finishDrawingKey: Esc
focusOnSelect: true
fontSize: 12
lineThickness: 2
yoloModelPath: ''
zoomOnSelect: true
zoomOnSelectLevel: fit
